version: "3.8"

services:
  app:
    container_name: cvwo-frontend
    image: cvwo-frontend
    ports: 
      - 8081:8081
    restart: always
    build:
      context: .
      target: production

networks:
  default:
    external: 
      name: cvwo