version: '3.8'
services:
  app:
    container_name: cvwo_backend
    build: .
    ports: 
      - 8080:8080 
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - backend-postgres
    networks:
      - cvwo


  backend-postgres:
    image: postgres:latest
    container_name: cvwo_db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./cvwo_backend.sql:/docker-entrypoint-initdb.d/cvwo_backend.sql
    networks:
      - cvwo

volumes:
  api:
  database_postgres:                 

# Networks to be created to facilitate communication between containers
networks:
  cvwo:
    external: 
      name: cvwo