version: "3.8"

services:
  cvwo-frontend:
    container_name: cvwo-frontend
    image: cvwo-frontend
    # Listen on both port 80 and 443
    ports: 
      - 80:80
      - 443:443
    restart: always
    environment:
      - TZ=Asia/Singapore
    build:
      context: .
      target: production
    volumes:
      - ./cvwo.conf:/etc/nginx/conf.d/cvwo.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    # Reload new SSL certificates from Let's Encrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot:latest
    restart: always
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # Renew SSL certificates if due for renewal
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# Network to be created to allow communication between frontend and backend
networks:
  default:
    external: 
      name: cvwo
